# This is a basic workflow to help you get started with Actions

name: timeout-minutes notification test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # 1分でタイムアウトする設定にする
    timeout-minutes: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # echoコマンドを打つ
      - name: run zero divide py
        run: |
          sleep 2m # timeout-minutesを超える時間sleepする
          python divide_zero.py
